const categories = {
    'sinks': [
        {title: 'Все', categoryUrl: 'all'},
        {title: 'Фарфор', categoryUrl: 'porcelain'},
        {title: 'Керамика', categoryUrl: 'ceramics'},
        {title: 'Акрил', categoryUrl: 'acrylic'},
        {title: 'Искуственный камень', categoryUrl: 'stone'},
    ],
    'taps': [
        {title: 'Все', categoryUrl: 'all'},
        {title: 'Встроенные', categoryUrl: 'taps-insink'},
        {title: 'Сенсорные', categoryUrl: 'taps-sensor'},
        {title: 'Ванны и душевые кабины', categoryUrl: 'taps-shower'},
        {title: 'Биде и гигиенический душ', categoryUrl: 'taps-sanitary'},
    ],
    'ranges': [
        {title: 'Все', categoryUrl: 'all'},
        {title: '1 конфорка', categoryUrl: 'range-single'},
        {title: '2 конфорки', categoryUrl: 'range-double'},
        {title: '3 конфорки', categoryUrl: 'range-triple'},
        {title: '4 конфорки', categoryUrl: 'range-4-way'},
        {title: '5 конфорок', categoryUrl: 'range-5-way'},
        {title: '6 конфорок', categoryUrl: 'range-6-way'},
    ],
    'washstands': [
        {title: 'Все', categoryUrl: 'all'},
        {title: 'Нержавеющая сталь', categoryUrl: 'washstands-stainless-steel'},
        {title: 'Окрашенные (Regi Color)', categoryUrl: 'washstands-porcelain'},
    ],
    'accessories': [
        {title: 'Все', categoryUrl: 'all'},
        {title: 'Разделочные доски', categoryUrl: 'accessories-boards'},
        {title: 'Корзины', categoryUrl: 'accessories-baskets'},
        {title: 'Коландеры', categoryUrl: 'accessories-dishwasher-bins'},
        {title: 'Решетки на дно/поддоны', categoryUrl: 'accessories-pans'},
        {title: 'Адаптеры и комплектующие', categoryUrl: 'accessories-adapters'},
        {title: 'Сифоны', categoryUrl: 'accessories-siphons'},
    ],
    'storage-manhattan': [
        {title: 'Все', categoryUrl: 'all'},
        {title: 'Manhattan', categoryUrl: 'storage-Manhattan'},
        {title: 'Manhattan Slim', categoryUrl: 'storage-manhattan-slim'},
        {title: 'Комплекты Manhattan', categoryUrl: 'storage-manhattan-kits'},
    ],
    'muscellaneous': [
        {title: 'Все', categoryUrl: 'all'},
        {title: 'Мойки Rodi (Португалия)', categoryUrl: 'muscellaneous-rodi'},
        {title: 'Мойки Whinstone (Россия)', categoryUrl: 'muscellaneous-whinstone'},
        {title: 'Мойки Rerih (Италия)', categoryUrl: 'muscellaneous-rerih'},
        {title: 'Мойки Status (Италия)', categoryUrl: 'muscellaneous-status'},
        {title: 'Смесители Armando Vicario (Италия)', categoryUrl: 'muscellaneous-armando-vicario'},
        {title: 'Смесители Webert (Италия)', categoryUrl: 'muscellaneous-tap-webert'},
        {title: 'Смесители Effepi (Италия)', categoryUrl: 'muscellaneous-effepi'},
        {title: 'Умывальники Webert (Италия)', categoryUrl: 'muscellaneous-washstands-webert'},
        {title: 'Аксессуары Webert (Италия)', categoryUrl: 'muscellaneous-accessories-webert'},
        {title: 'Аксессуары Glionna Bagno (Италия)', categoryUrl: 'muscellaneous-glionna-bagno'},
        {title: 'Аквафор (Россия)', categoryUrl: 'muscellaneous-aquafor'},
    ],
};

module.exports = categories;