const sertificates = [
    {
        id: 'NrJkXB',
        name: 'Авторизованный диллер webert',
        img: 'authorized.webert.webp',
        alt: 'sertificate',
        width: '744',
        height: '1028',
    },
    {
        id: 'OblGmY',
        name: 'Официальный дистрибьютер Проминтех',
        img: 'certificate-of-authorisation-fraisa_rus.webp',
        alt: 'sertificate',
        width: '1061',
        height: '1500',
    },
    {
        id: 'fNlzsu',
        name: 'Kordi GmbH дистрибьютер',
        img: 'sert2014_2.webp',
        alt: 'sertificate',
        width: '1671',
        height: '2362',
    },
    {
        id: 'qdjEsI',
        name: 'ITE Group PLc',
        img: 'mbnew10.webp',
        alt: 'sertificate',
        width: '731',
        height: '1044',
    },
    {
        id: 'RISsYr',
        name: 'Санитарно техническая экспертиза',
        img: 'e3_2.webp',
        alt: 'sertificate',
        width: '921',
        height: '1307',
    },
    {
        id: 'TWQFqP',
        name: 'Корди MosBuild',
        img: 'MosBuild.webp',
        alt: 'sertificate',
        width: '610',
        height: '872',
    },
    {
        id: 'nncOII',
        name: 'The ITE Group Евросант',
        img: 'mbnew11.webp',
        alt: 'sertificate',
        width: '731',
        height: '1044',
    },
    {
        id: 'BPYuBd',
        name: 'Mitutoyo',
        img: 'MITUTOYO-2018.webp',
        alt: 'sertificate',
        width: '600',
        height: '849',
    },
    {
        id: 'cMrGKu',
        name: 'Mos Build выставка',
        img: 'di-BI77AW.webp',
        alt: 'sertificate',
        width: '1000',
        height: '1409',
    },
    {
        id: 'TCqLDV',
        name: 'e3 Awwards',
        img: 'e3_1.webp',
        alt: 'sertificate',
        width: '921',
        height: '1317',
    },
    {
        id: 'FmCpby',
        name: 'Mos Build 2014',
        img: 'di-FWFUGM.webp',
        alt: 'sertificate',
        width: '1000',
        height: '1413',
    },
    {
        id: 'odHldb',
        name: 'ГОСТ ISO 9001-2008',
        img: '7232438.webp',
        alt: 'sertificate',
        width: '537',
        height: '768',
    },
    {
        id: 'yrXjQI',
        name: 'ARTIS Srl',
        img: 'certificate-artis-2018-2021.webp',
        alt: 'sertificate',
        width: '700',
        height: '988',
    },
    {
        id: 'JAJHFp',
        name: 'Душевая сантехника',
        img: 'byonsert.webp',
        alt: 'sertificate',
        width: '686',
        height: '899',
    },
    {
        id: 'kFyONj',
        name: 'Арматура и сантехника',
        img: 'sertif_12_b.webp',
        alt: 'sertificate',
        width: '600',
        height: '845',
    },
    {
        id: 'pNvNlQ',
        name: 'Forbs & Company',
        img: 'totem_iso-9001_2008.webp',
        alt: 'sertificate',
        width: '700',
        height: '991',
    },
    {
        id: '',
        name: 'Краны и смесители для кухонных моек',
        img: 'sertificate_2017.webp',
        alt: 'sertificate',
        width: '600',
        height: '829',
    },
    {
        id: 'aEknnx',
        name: 'Reginox approval',
        img: 'Certificaat_ISO_9001_2015.webp',
        alt: 'sertificate',
        width: '1178',
        height: '1689',
    },
    {
        id: 'NKVYMG',
        name: 'Сертификат соответствия H08858',
        img: 'sertif_14_b.webp',
        alt: 'sertificate',
        width: '600',
        height: '844',
    },
];

module.exports = sertificates;