export const REQUEST = '_REQUEST';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';

export const LOAD_MENU = 'LOAD_MENU';
export const LOAD_HOME = 'LOAD_HOME';
export const LOAD_CATALOGS = 'LOAD_CATALOGS';
export const LOAD_SERTIFICATES = 'LOAD_SERTIFICATES';
export const LOAD_BRANDS = 'LOAD_BRANDS';
export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const LOAD_ARTICLE = 'LOAD_ARTICLE';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const LOAD_REVIEWS = 'LOAD_REVIEWS';
export const LOAD_CART = 'LOAD_CART';
export const LOAD_SIMILAR_RPODUCTS = 'LOAD_SIMILAR_RPODUCTS';
export const LOAD_PROMO_ITEMS = 'LOAD_PROMO_ITEMS';
export const LOAD_NEW_ITEMS = 'LOAD_NEW_ITEMS';
export const LOAD_COMPARE_ITEMS = 'LOAD_COMPARE_ITEMS';
export const SUBMIT_ORDER = 'SUBMIT_ORDER';

export const APP_SET_TILES = 'APP_SET_TILES';
export const APP_UNSET_TILES = 'APP_UNSET_TILES';
export const APP_OPEN_SEARCH = 'OPEN_SEARCH';
export const APP_CLOSE_SEARCH = 'CLOSE_SEARCH';
export const APP_SET_ERROR = 'APP_SET_ERROR';
export const APP_UNSET_ERROR = 'APP_UNSET_ERROR';

export const ARTICLES_SELECT_PAGE = 'ARTICLES_SELECT_PAGE';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_CLEAR = 'CART_CLEAR';

export const COMPARE_TOGGLE_ITEM = 'COMPARE_TOGGLE_ITEM';
export const COMPARE_REMOVE_ITEM = 'COMPARE_REMOVE_ITEM';

export const FILTERS_IS_FILTERED = 'FILTERS_IS_FILTERED';
export const FILTERS_IS_FILTERING = 'FILTERS_IS_FILTERING';
export const FILTERS_SORT_PRODUCTS_INIT = 'FILTERS_SORT_PRODUCTS_INIT';

export const ORDER_CLOSE_MODAL = 'ORDER_CLOSE_MODAL';