export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';

export const LOAD_CATALOG = 'LOAD_CATALOG';
export const LOAD_HOME = 'LOAD_HOME';
export const LOAD_CATALOGS = 'LOAD_CATALOGS';
export const LOAD_SERTIFICATES = 'LOAD_SERTIFICATES';
export const LOAD_BRANDS = 'LOAD_BRANDS';
export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const LOAD_ARTICLE = 'LOAD_ARTICLE';
export const LOAD_FILTERS = 'LOAD_FILTERS';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';

export const SELECT_PRODUCTS_ID = 'SELECT_PRODUCTS_ID';

export const SELECT_ARTICLES_PAGE = 'SELECT_ARTICLES_PAGE';

export const OPEN_MAIN_MENU = 'OPEN_MAIN_MENU';
export const OPEN_FILTERS_MENU = 'OPEN_FILTERS_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';

export const SET_SERTIFICATES_SLIDER_SLIDE = 'SET_SERTIFICATES_SLIDER_SLIDE';
export const SET_SERTIFICATES_SCROLL = 'SET_SERTIFICATES_SCROLL';

export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';