export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';

export const SET_APP_STATUS = 'SET_APP_STATUS';
export const SET_APP_HOME_PAGE = 'SET_APP_HOME_PAGE';
export const SET_APP_IS_POP_UP = 'SET_APP_IS_POP_UP';
export const SET_APP_TILES = 'SET_APP_TILES';
export const UNSET_APP_TILES = 'UNSET_APP_TILES';

export const LOAD_MENU = 'LOAD_MENU';
export const LOAD_HOME = 'LOAD_HOME';
export const LOAD_CATALOGS = 'LOAD_CATALOGS';
export const LOAD_SERTIFICATES = 'LOAD_SERTIFICATES';
export const LOAD_BRANDS = 'LOAD_BRANDS';
export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const LOAD_ARTICLE = 'LOAD_ARTICLE';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const LOAD_REVIEWS = 'LOAD_REVIEWS';
export const LOAD_CART = 'LOAD_CART';
export const LOAD_SIMILAR_RPODUCTS = 'LOAD_SIMILAR_RPODUCTS';
export const LOAD_PROMO_ITEMS = 'LOAD_PROMO_ITEMS';
export const LOAD_NEW_ITEMS = 'LOAD_NEW_ITEMS';
export const LOAD_COMPARE_ITEMS = 'LOAD_COMPARE_ITEMS';

export const TOGGLE_COMPARE_ITEM = 'TOGGLE_COMPARE_ITEM';
export const REMOVE_ITEM_FROM_COMPARE = 'REMOVE_ITEM_FROM_COMPARE';
export const RESET_COMPARE_LOADED = 'RESET_COMPARE_LOADED';

export const SELECT_ARTICLES_PAGE = 'SELECT_ARTICLES_PAGE';

export const OPEN_MAIN_MENU = 'OPEN_MAIN_MENU';
export const OPEN_FILTERS_MENU = 'OPEN_FILTERS_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';

export const SET_SERTIFICATES_SLIDER_SLIDE = 'SET_SERTIFICATES_SLIDER_SLIDE';
export const SET_SERTIFICATES_SCROLL = 'SET_SERTIFICATES_SCROLL';

export const TOGGLE_PRODUCTS_IS_FILTERING = 'TOGGLE_PRODUCTS_IS_FILTERING';
export const PRODUCTS_IS_FILTERED = 'PRODUCTS_IS_FILTERED';
export const PRODUCTS_IS_FILTERING = 'PRODUCTS_IS_FILTERING';
export const SETLECT_PRODUCTS_SORT_BY = 'SETLECT_PRODUCTS_SORT_BY';

export const SET_QUERY_STRING = 'SET_QUERY_STRING';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
